name: Deploy Substrate Nodes

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@main
      with:
        version: 'latest'
        project_id: 'dogextestnet'
        service_account_key: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Initialize Terraform
      run: terraform init

    - name: Plan Terraform
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}
      run: terraform plan -var "google_credentials=${{ secrets.GCP_SA_KEY }}" -var "project_id=dogextestnet" -out=tfplan

    - name: Apply Terraform
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}
      run: terraform apply "tfplan"